Matsuri2:
  lout -F afm Matsuri2.lout -o tmp.ps; 
  gs "-sFONTPATH=/usr/local/share/fonts/Font/Western Fonts/Warnock Pro/Subhead/" -dNOPAUSE -dBATCH -sDEVICE=pdfwrite -dEmbedAllFonts=true -sOutputFile=Matsuri2.pdf tmp.ps
  evince Matsuri2.pdf &

Takinobori:
  lout -PDF -F afm Takinobori.lout -o tmp.pdf
  gs "-sFONTPATH=/usr/local/share/fonts/Font/Western Fonts/Warnock Pro/Subhead/" -dNOPAUSE -dBATCH -sDEVICE=pdfwrite -dEmbedAllFonts=true -sOutputFile=Takinobori.pdf tmp.pdf
  evince Takinobori.pdf &

Taki1:
  lout -F afm Taki1.lout -o tmp.ps; 
  gs "-sFONTPATH=/usr/local/share/fonts/Font/Western Fonts/Warnock Pro/Subhead/" -dNOPAUSE -dBATCH -sDEVICE=pdfwrite -dEmbedAllFonts=true -sOutputFile=Taki1.pdf tmp.ps
  evince Taki1.pdf &

Shukusei:
  lout -F afm Shukusei.lout -o tmp.ps; 
  gs "-sFONTPATH=/usr/local/share/fonts/Font/Western Fonts/Warnock Pro/Subhead/" -dNOPAUSE -dBATCH -sDEVICE=pdfwrite -dEmbedAllFonts=true -sOutputFile=Shukusei.pdf tmp.ps
  evince Shukusei.pdf &
